# based on https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  create:
    branches: 
      - release/**
  push:
    branches:
      - main
  pull_request:

concurrency:
  # For pull requests, cancel all currently-running jobs for this workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '6.0.x', '7.0.x']

    steps:
      - uses: actions/checkout@v3

      - name: Get Build Version
        run: |
          Import-Module .\.github\workflows\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Echo Build Version
        run: echo $BUILD_VERSION

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: List .NET SDKs
        run: dotnet --list-sdks

      - name: Restore project dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

      - name: Run tests
        run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release') && contains(matrix.dotnet-version, '7.0.x')
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}